# Find all elements which name starts with the letter “C”.

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX table: <http://www.daml.org/2003/01/periodictable/PeriodicTable#>

SELECT ?name
WHERE {
	?element table:name ?name;
 		rdf:type table:Element.
	FILTER ( regex(?name, "^c"))
}
ORDER BY ?element